# Generated by Django 2.2 on 2021-06-22 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('0', 'Общие вопросы'), ('1', 'Финансовый'), ('2', 'Технический'), ('3', 'Баги/проблемы сайта')], default=0, max_length=128, verbose_name='Выберите отдел')),
                ('title', models.CharField(max_length=128, verbose_name='Причина')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ от тех.поддержки')),
                ('status', models.CharField(choices=[('0', 'Открыт'), ('1', 'Ожидает ответа'), ('2', 'Закрыт')], default=0, max_length=128, verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'тикет',
                'verbose_name_plural': 'тикеты',
                'ordering': ['-date', '-status'],
            },
        ),
    ]
