# Generated by Django 2.2 on 2021-06-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210622_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Тема'),
        ),
    ]
