# Generated by Django 2.2 on 2021-06-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210622_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
